/* ========= DECLARACIÓN DE PARÁMETROS ========= */

DECLARE @NRO_FACTURA VARCHAR(14);
SET @NRO_FACTURA = 'A0133101858736';

DECLARE @CUIT_PROVEEDOR VARCHAR(11);
SET @CUIT_PROVEEDOR = '30663288497';

DECLARE @COD_CONCEPTO VARCHAR(3);
SET @COD_CONCEPTO = '038';

DECLARE @LEYENDA VARCHAR(30);
SET @LEYENDA = '';

DECLARE @NOMBRE_COMPLETO VARCHAR(120);
SET @NOMBRE_COMPLETO = 'Gustavo Agüero';

DECLARE @TIPO_FACTURA VARCHAR(1);
SET @TIPO_FACTURA = 'C';

DECLARE @CAE VARCHAR(15);
SET @CAE = '86040983248736';

DECLARE @F_CONTABLE VARCHAR(8);
SET @F_CONTABLE = '20260122';

DECLARE @F_EMISION VARCHAR(8);
SET @F_EMISION = '20260122';

DECLARE @F_VTO_CAE VARCHAR(8);
SET @F_VTO_CAE = '20260201';

DECLARE @ID_SECTOR DECIMAL(18,2);
SET @ID_SECTOR = 4;

DECLARE @ID_AUXILIAR DECIMAL(18,2);
SET @ID_AUXILIAR = 2;

DECLARE @ID_PERCEPCION DECIMAL(18,2);
SET @ID_PERCEPCION = -1;

DECLARE @ID_PERCEPCION2 DECIMAL(18,2);
SET @ID_PERCEPCION2 = 13;

DECLARE @ID_SESION DECIMAL(18,2);
SET @ID_SESION = 0;

DECLARE @IMPORTE_GRAVADO DECIMAL(18,2);
SET @IMPORTE_GRAVADO = 198612.50;

DECLARE @IMPORTE_NO_GRAVADO DECIMAL(18,2);
SET @IMPORTE_NO_GRAVADO = 0.00;

DECLARE @IMPORTE_IVA_21 DECIMAL(18,2);
SET @IMPORTE_IVA_21 = 10417.31;

DECLARE @IMPORTE_IVA_105 DECIMAL(18,2);
SET @IMPORTE_IVA_105 = 0.00;

DECLARE @IMPORTE_IVA_27 DECIMAL(18,2);
SET @IMPORTE_IVA_27 = 40231.69;

DECLARE @IMPORTE_IVA_5 DECIMAL(18,2);
SET @IMPORTE_IVA_5 = 0.00;

DECLARE @IMPORTE_IVA_25 DECIMAL(18,2);
SET @IMPORTE_IVA_25 = 0.00;

DECLARE @IMPORTE_TOTAL DECIMAL(18,2);
SET @IMPORTE_TOTAL = 263062.32;

DECLARE @IMPORTE_PERCEPCION DECIMAL(18,2);
SET @IMPORTE_PERCEPCION = 0;

DECLARE @IMPORTE_PERCEPCION2 DECIMAL(18,2);
SET @IMPORTE_PERCEPCION2 = 13800.82;

DECLARE @NO_GRAVADO_OTROS DECIMAL(18,2);
SET @NO_GRAVADO_OTROS = 0;


/* ========= SCRIPT ORIGINAL ========= */

SET NOCOUNT ON;
DECLARE @RESULTADO VARCHAR(1000) = 'OK';
DECLARE @NCOMP_IN_C NUMERIC(18,0) = 0;

BEGIN TRY
BEGIN TRAN
DECLARE @SQL Nvarchar(max)
DECLARE @ID_ASIENTO_COMPROBANTE_CP NUMERIC(18, 0)
DECLARE @COD_PROVEE  VARCHAR(6)
DECLARE @CAT_IVA  VARCHAR(3)
DECLARE @COD_IVA_21  VARCHAR(2)
DECLARE @COD_IVA_105  VARCHAR(2)
DECLARE @COD_IVA_27  VARCHAR(2)
DECLARE @COND_COMPRA  VARCHAR(2)
DECLARE @ID_CPA04  NUMERIC(18, 0)
DECLARE @ID_ASIENTO_MODELO_CP  NUMERIC(18, 0)
DECLARE @ID_ASIENTO_CP  NUMERIC(18, 0)
DECLARE @ID_CUENTA_PROVEEDORES  NUMERIC(18, 0)
DECLARE @ID_CUENTA_IVA NUMERIC(18, 0)
DECLARE @ID_CUENTA_GASTO  NUMERIC(18, 0)

DECLARE @PORC_PERCEPCION AS NUMERIC(18,2)

DECLARE @COD_PERCEPCION AS NUMERIC(5,0)
DECLARE @COD_PERCEPCION2 AS NUMERIC(5,0)

DECLARE @CLAS_SIAP AS VARCHAR(3)				
DECLARE @COD_SECTOR AS VARCHAR(5)
DECLARE @COD_DEPOSITO AS VARCHAR(3)
DECLARE @TIPO_COMP AS VARCHAR(1)
DECLARE @ID_CPA46 AS NUMERIC(18,0)
DECLARE @NCOMP_IN_S AS VARCHAR(8)
DECLARE @ESTADO_STK AS VARCHAR(1)
DECLARE @TCOMP_IN_C AS VARCHAR(2)
DECLARE @ID_CUENTA_SB AS NUMERIC(18)
DECLARE @USA_AUX CHAR(1);

IF @ID_SECTOR<>-1
		SET @COD_SECTOR= (SELECT COD_SECTOR FROM CPA51 WHERE ID_CPA51=@ID_SECTOR)
	ELSE 
		BEGIN
		SET @COD_SECTOR =''
		END
	
	IF @ID_PERCEPCION <>-1 
		BEGIN 
			SET @COD_PERCEPCION = (sELECT COD_IVA FROM CPA14 WHERE ID_CPA14=@ID_PERCEPCION)
			SET @PORC_PERCEPCION = (sELECT PORC_IVA  FROM CPA14 WHERE ID_CPA14=@ID_PERCEPCION)
		END

	IF @ID_PERCEPCION2 <>-1 
			SET @COD_PERCEPCION2 = (sELECT COD_IVA FROM CPA14 WHERE ID_CPA14=@ID_PERCEPCION2)
			
	
	SET @IMPORTE_NO_GRAVADO = @IMPORTE_NO_GRAVADO + @NO_GRAVADO_OTROS

	IF @IMPORTE_IVA_21 = 0  
		SET @COD_IVA_21 =0
	else
		BEGIN
			SET @COD_IVA_21 =(SELECT COD_IVA_21 from rba_configuracion_pi)
		end 

	if @IMPORTE_IVA_105 = 0  
		SET @COD_IVA_105 =0
	else
		BEGIN
			SET @COD_IVA_105 =(SELECT COD_IVA_105 from rba_configuracion_pi)
		end 

	if @IMPORTE_IVA_27 = 0  
		SET @COD_IVA_27 =0
	else
		BEGIN
			SET @COD_IVA_27 =(SELECT COD_IVA_27 from rba_configuracion_pi)
		end 

	SET @COND_COMPRA = (SELECT COND_COMPRA FROM RBA_CONFIGURACION_PI)
	SET @ID_CPA46 = (SELECT MAX(ID_CPA46) ID_CPA46 FROM CPA46)
	SET @ID_ASIENTO_MODELO_CP =(SELECT ID_ASIENTO_MODELO_CP FROM RBA_CONFIGURACION_PI)
	SET @RESULTADO ='' 
	SET @NCOMP_IN_C = (select isnull(max(NComp_In_C), 0)+1 from Cpa04 where TComp_In_C in ( 'FS', 'FP', 'DP', 'CP'))
	SET @ID_CUENTA_PROVEEDORES=(SELECT ID_CUENTA FROM RENGLON_MODELO_CP  inner join TIPO_CONTABLE on RENGLON_MODELO_CP.ID_TIPO_CONTABLE =tipo_contable.ID_TIPO_CONTABLE 
		where id_asiento_modelo_cp=@ID_ASIENTO_MODELO_CP and COD_TIPO_CONTABLE ='TO')
	SET @ID_CUENTA_SB=(SELECT ID_CUENTA FROM RENGLON_MODELO_CP  inner join TIPO_CONTABLE on RENGLON_MODELO_CP.ID_TIPO_CONTABLE =tipo_contable.ID_TIPO_CONTABLE 
		where id_asiento_modelo_cp=@ID_ASIENTO_MODELO_CP and COD_TIPO_CONTABLE ='SB')
	IF @TIPO_FACTURA ='C'
		BEGIN
		SET @ESTADO_STK =''
		SET @TCOMP_IN_C ='FP'
		SET @TIPO_COMP='C'
		END
	ELSE 
		BEGIN
		SET @ESTADO_STK='F'
		SET @TCOMP_IN_C ='FS'
		SET @COD_DEPOSITO = (SELECT COD_DEPOSITO FROM RBA_CONFIGURACION_PI)
		SET @TIPO_COMP='A'
		END
		


	SET @COD_PROVEE = (SELECT top 1 COD_PROVEE FROM CPA01 WHERE fecha_inha = '1800-01-01 00:00:00.000' and N_CUIT = LEFT(@CUIT_PROVEEDOR,2) + '-' + SUBSTRING(@CUIT_PROVEEDOR,3,8)+'-' + RIGHT (@CUIT_PROVEEDOR,1) )
	IF NOT EXISTS (SELECT TOP 1 COD_PROVEE FROM CPA01 WHERE fecha_inha = '1800-01-01 00:00:00.000' and N_CUIT = LEFT(@CUIT_PROVEEDOR,2) + '-' + SUBSTRING(@CUIT_PROVEEDOR,3,8)+'-' + RIGHT (@CUIT_PROVEEDOR,1))
	BEGIN
		SET @RESULTADO ='El proveedor cuyo CUIT es ' + @CUIT_PROVEEDOR + ' no existe en la base de datos, debe generarlo antes de continuar.'
		set @NCOMP_IN_C=0
	END
	
	ELSE
		IF EXISTS (SELECT TOP 1 NCOMP_IN_C FROM CPA04 WHERE N_COMP = @NRO_FACTURA AND COD_PROVEE = @COD_PROVEE )
			begin
			SET @NCOMP_IN_C=(SELECT TOP 1 NCOMP_IN_C FROM CPA04 WHERE N_COMP = @NRO_FACTURA AND COD_PROVEE = @COD_PROVEE )
			SET @RESULTADO ='La factura Nro.' + @NRO_FACTURA + ' del proveedor cuyo codigo es: ' + @COD_PROVEE + ' ya existe bajo el nro de interno: ' + 
			cast(@NCOMP_IN_C as varchar) + '. No se puede completar la operacion.'
			
			END
		else 
		BEGIN
			SET @COD_PROVEE = (SELECT TOP 1 COD_PROVEE FROM CPA01 WHERE fecha_inha = '1800-01-01 00:00:00.000' and N_CUIT = LEFT(@CUIT_PROVEEDOR,2) + '-' + SUBSTRING(@CUIT_PROVEEDOR,3,8)+'-' + RIGHT (@CUIT_PROVEEDOR,1))
			SET @CAT_IVA = (SELECT TOP 1 COND_IVA FROM CPA01 WHERE COD_PROVEE = @COD_PROVEE )

			------CPA04
			
			INSERT INTO CPA04  (
			FILLER, BARRA_FON, CAI, CAT_IVA, CITI_OPERA, CITI_TIPO, COD_GASTO, 
			COD_IVA1, 			COD_IVA2,  			COD_IVA3,			COD_IVA4, COD_IVA5,
			COD_PROVEE,COD_SECTOR,COMP_AFIP,COND_COMPR, CONTABILIZ, CONTFISCAL, COTIZACION, DESPACHO,
			ESTADO,	ESTADO_AUT, ESTADO_STK, FECHA_CONT, FECHA_EMIS, FECHA_VTO, 
			IMP_IVA1,			IMP_IVA2,		IMP_IVA3,  			IMP_IVA4,
			IMP_IVA5, IMPORTE_AN, IMPORTE_BO, IMPORTE_EX, IMPORTE_FL, 
			IMPORTE_IN, IMPORTE_NE, IMPORTE_TO, INC_II, INC_IVA,
			LEYENDA, LOTE, MON_CTE, N_COMP, N_COMP_FON, NCOMP_IN_C, PORC_BONIF, 
			PORC_IVA1, 			PORC_IVA2,  			PORC_IVA3, 
			PORC_IVA4, PORC_IVA5, SUBT_EXENT, SUBT_GRAVA, T_COMP, T_COMP_FON, TCOMP_IN_C, TIPO_ASIEN, TIPO_COMPR, TIPO_IMPOR, 
			UNIDADES, HORA, DIFERENCIA, EXPORTADO, NRO_SUCURS, CCONTROL, BO_AUTORIZ, DOC_ELECTR, CAICAE_VTO, MO_NO_CRED, 
			INF_IVA, CAICAE, T_DOC_DTE, N_INT_MES, IVA_CHILE, SUCURS_SII, CERRADO, COD_CLASIF, AFECTO_AF, EXENTO_AF,
			IVA_AF,	ACTIVOFIJO, ID_ASIENTO_MODELO_CP, GENERA_ASIENTO, FECHA_INGRESO, HORA_INGRESO, USUARIO_INGRESO, TERMINAL_INGRESO,
			FECHA_ULTIMA_MODIFICACION, HORA_ULTIMA_MODIFICACION, 
			USUA_ULTIMA_MODIFICACION, TERM_ULTIMA_MODIFICACION, N_INT_ORI, T_INT_ORI, RG_3572_TIPO_OPERACION_HABITUAL_COMPRAS, RG_3572_CUIT_INTERMEDIARIO, COD_NO_RECUP, BO_TIPO_COMPRA, BO_ES_COMBUSTIBLE, RG_3572_DENOMINACION_INTERMEDIARIO, 
			RG_3685_TIPO_OPERACION_COMPRAS, RG_3685_COMPROBANTE_COMPRAS, RG_3685_IVA_COMISION, IMPORTE_FLETE_RENGLON, SUBTOTAL_FLETE_RENGLON, TIPO_TRANSACCION_VENTA, TIPO_TRANSACCION_COMPRA, ESTADO_UNIDADES, TALONARIO, MOTIVO_ANULACION_OP,
			FECHA_ANULACION_OP, CONVERSOR_CLAUSULA_DIFERENCIA_ESTADOS,	COD_CPA01, NRO_SUCURSAL_DESTINO, OBSERVACIONES ) 
			VALUES (
			'', 0, @CAE, @CAT_IVA, 'O', 'B', '', 

			--COD_IVA1, 
			CASE WHEN @COD_IVA_21 <>0 THEN @COD_IVA_21 
			ELSE CASE WHEN @COD_IVA_105 <>0 THEN @COD_IVA_105 
			ELSE CASE WHEN @COD_IVA_27 <>0 THEN @COD_IVA_27 ELSE 
			CASE WHEN  (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51)  THEN @COD_PERCEPCION ELSE 0 END END END END,
			--COD_IVA2
			CASE WHEN (@COD_IVA_21 <>0 AND @COD_IVA_105<>0) THEN @COD_IVA_105 
			ELSE CASE WHEN (@COD_IVA_21 <> 0 and @COD_IVA_105 = 0 and @COD_IVA_27 <>0) OR (@COD_IVA_21 = 0 and @COD_IVA_105 <> 0 and @COD_IVA_27 <>0) then @COD_IVA_27
			ELSE CASE WHEN (@COD_IVA_21 <> 0 and @COD_IVA_105 = 0 and @COD_IVA_27 = 0) AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51) THEN @COD_PERCEPCION 	
			ELSE CASE WHEN (@COD_IVA_21 = 0 and @COD_IVA_105 <> 0 and @COD_IVA_27 = 0) AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51) THEN @COD_PERCEPCION
			ELSE CASE WHEN (@COD_IVA_21 = 0 and @COD_IVA_105 = 0 and @COD_IVA_27 <> 0) AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51) THEN @COD_PERCEPCION
			ELSE 0 END END END END END,

			--COD_IVA3
			CASE WHEN (@COD_IVA_21 <>0 ) and (@COD_IVA_105<>0) and ( @COD_IVA_27 <>0) THEN @COD_IVA_27 ELSE
			CASE WHEN (@COD_IVA_21 <> 0 AND @COD_IVA_105 <> 0 AND @COD_IVA_27 = 0 AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51)) THEN @COD_PERCEPCION ELSE
			CASE WHEN (@COD_IVA_21 <> 0 AND @COD_IVA_105 = 0 AND @COD_IVA_27 <> 0 AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51)) THEN @COD_PERCEPCION ELSE
			CASE WHEN (@COD_IVA_21 = 0 AND @COD_IVA_105 <> 0 AND @COD_IVA_27 <> 0 AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51)) THEN @COD_PERCEPCION ELSE 0 END END END END ,  

			--COD_IVA4
			CASE WHEN (@COD_IVA_21 <>0  and @COD_IVA_105<>0 and  @COD_IVA_27 <>0 AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51)) THEN @COD_PERCEPCION ELSE 0 END ,  

			--COD_IVA5
			0, 
			
			@COD_PROVEE, @COD_SECTOR, 0, @COND_COMPRA, 0, 0, 1.0000000,'',
			'PEN', '', @ESTADO_STK, @F_CONTABLE, @F_EMISION,'1800-01-01 00:00:00', 

			--IMPORTE_IVA1, 
			CASE WHEN @COD_IVA_21 <>0 THEN @IMPORTE_IVA_21 
			ELSE CASE WHEN @COD_IVA_105 <>0 THEN @IMPORTE_IVA_105 
			ELSE CASE WHEN @COD_IVA_27 <>0 THEN @IMPORTE_IVA_27 ELSE 
			CASE WHEN  (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51) THEN @IMPORTE_PERCEPCION ELSE 0 END END END END,---

			--IMPORTE_IVA2
			CASE WHEN (@COD_IVA_21 <>0 AND @COD_IVA_105<>0) THEN @IMPORTE_IVA_105 
			ELSE CASE WHEN (@COD_IVA_21 <> 0 and @COD_IVA_105 = 0 and @COD_IVA_27 <>0) OR (@COD_IVA_21 = 0 and @COD_IVA_105 <> 0 and @COD_IVA_27 <>0) then @IMPORTE_IVA_27
			ELSE CASE WHEN (@COD_IVA_21 <> 0 and @COD_IVA_105 = 0 and @COD_IVA_27 = 0) AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51) THEN @IMPORTE_PERCEPCION 	
			ELSE CASE WHEN (@COD_IVA_21 = 0 and @COD_IVA_105 <> 0 and @COD_IVA_27 = 0) AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51) THEN @IMPORTE_PERCEPCION
			ELSE CASE WHEN (@COD_IVA_21 = 0 and @COD_IVA_105 = 0 and @COD_IVA_27 <> 0) AND @COD_PERCEPCION<>0 THEN @IMPORTE_PERCEPCION
			ELSE 0 END END END END END,

			--IMPORTE_IVA3
			CASE WHEN (@COD_IVA_21 <>0 ) and (@COD_IVA_105<>0) and ( @COD_IVA_27 <>0) THEN @IMPORTE_IVA_27 ELSE
			CASE WHEN (@COD_IVA_21 <> 0 AND @COD_IVA_105 <> 0 AND @COD_IVA_27 = 0 AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51)) THEN @IMPORTE_PERCEPCION ELSE
			CASE WHEN (@COD_IVA_21 <> 0 AND @COD_IVA_105 = 0 AND @COD_IVA_27 <> 0 AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51)) THEN @IMPORTE_PERCEPCION ELSE
			CASE WHEN (@COD_IVA_21 = 0 AND @COD_IVA_105 <> 0 AND @COD_IVA_27 <> 0 AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51)) THEN @IMPORTE_PERCEPCION ELSE 0 END END END END ,  

			--IMPORTE_IVA4
			CASE WHEN (@COD_IVA_21 <>0  and @COD_IVA_105<>0 and  @COD_IVA_27 <>0 AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51)) THEN @IMPORTE_PERCEPCION ELSE 0 END ,  



			 
			0, 0, 0, @IMPORTE_NO_GRAVADO, 0, 0, @IMPORTE_GRAVADO, @IMPORTE_TOTAL, 0, 0,
			@LEYENDA, 0, 1, @NRO_FACTURA, '', @NCOMP_IN_C, 0, 

			
			--PORC_IVA1, 
			CASE WHEN @COD_IVA_21 <>0 THEN 21 
			ELSE CASE WHEN @COD_IVA_105 <>0 THEN 10.5 
			ELSE CASE WHEN @COD_IVA_27 <>0 THEN 27 ELSE 
			CASE WHEN  (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51) THEN @PORC_PERCEPCION  ELSE 0 END END END END,---

			--PORC_IVA2
			CASE WHEN (@COD_IVA_21 <>0 AND @COD_IVA_105<>0) THEN 10.5 
			ELSE CASE WHEN (@COD_IVA_21 <> 0 and @COD_IVA_105 = 0 and @COD_IVA_27 <>0) OR (@COD_IVA_21 = 0 and @COD_IVA_105 <> 0 and @COD_IVA_27 <>0) then 27
			ELSE CASE WHEN (@COD_IVA_21 <> 0 and @COD_IVA_105 = 0 and @COD_IVA_27 = 0) AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51) THEN @PORC_PERCEPCION 	
			ELSE CASE WHEN (@COD_IVA_21 = 0 and @COD_IVA_105 <> 0 and @COD_IVA_27 = 0) AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51) THEN @PORC_PERCEPCION
			ELSE CASE WHEN (@COD_IVA_21 = 0 and @COD_IVA_105 = 0 and @COD_IVA_27 <> 0) AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51) THEN @PORC_PERCEPCION
			ELSE 0 END END END END END,

			--PORC_IVA3
			CASE WHEN (@COD_IVA_21 <>0 ) and (@COD_IVA_105<>0) and ( @COD_IVA_27 <>0) THEN 27 ELSE
			CASE WHEN (@COD_IVA_21 <> 0 AND @COD_IVA_105 <> 0 AND @COD_IVA_27 = 0 AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51)) THEN @PORC_PERCEPCION ELSE
			CASE WHEN (@COD_IVA_21 <> 0 AND @COD_IVA_105 = 0 AND @COD_IVA_27 <> 0 AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51)) THEN @PORC_PERCEPCION ELSE
			CASE WHEN (@COD_IVA_21 = 0 AND @COD_IVA_105 <> 0 AND @COD_IVA_27 <> 0 AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51)) THEN @PORC_PERCEPCION ELSE 0 END END END END ,  

			--PORC_IVA4
			CASE WHEN (@COD_IVA_21 <>0  and @COD_IVA_105<>0 and  @COD_IVA_27 <>0 AND (@COD_PERCEPCION <>0 AND @COD_PERCEPCION <51)) THEN @PORC_PERCEPCION ELSE 0 END ,  

			
			
			0, @IMPORTE_NO_GRAVADO, @IMPORTE_GRAVADO,'FAC','',@TCOMP_IN_C, '', @TIPO_COMP ,'', 
			@IMPORTE_TOTAL , '000000','N', 0, 0,'', 0, 0, @F_VTO_CAE, '', 
			'S', '', '', 0, '', 0, 0, '', 0, 0, 
			0,	'N', @ID_ASIENTO_MODELO_CP, 'S', GETDATE(), '00000', @NOMBRE_COMPLETO,'PI','1800-01-01 00:00:00','',
			'',	'',	0, '', '', '','', 0, 0,'',
			'0',CASE LEFT(@NRO_FACTURA,1) WHEN 'A' THEN '001' ELSE '011' END, 0, 0, 0, 0, 0,'PEN', 0, '', 
			'1800-01-01 00:00:00',	'', '', '','' )
			
			SET @ID_CPA04=(SELECT ID_CPA04 FROM CPA04 WHERE NCOMP_IN_C= @NCOMP_IN_C AND TCOMP_IN_C =@TCOMP_IN_C)
			--CPA18
			IF @COD_PERCEPCION >=51
				INSERT INTO CPA18 (FILLER, COD_IMPUES, COD_PROVEE, F_COMP, IMPORTE,NCOMP_IN_C,TCOMP_IN_C,COD_PROV,COD_SII)
				VALUES ('', @COD_PERCEPCION, @COD_PROVEE, @F_CONTABLE, @IMPORTE_PERCEPCION, @NCOMP_IN_C, @TCOMP_IN_C,'','')
			--CPA18
			IF @COD_PERCEPCION2 >=51
				INSERT INTO CPA18 (FILLER, COD_IMPUES, COD_PROVEE, F_COMP, IMPORTE,NCOMP_IN_C,TCOMP_IN_C,COD_PROV,COD_SII)
				VALUES ('', @COD_PERCEPCION2, @COD_PROVEE, @F_CONTABLE, @IMPORTE_PERCEPCION2, @NCOMP_IN_C, @TCOMP_IN_C,'','')
			--cpa54 CUOTA
			INSERT INTO CPA54 (
			FILLER, COD_PROVEE, ESTADO_AUT, ESTADO_VTO, FECHA_VTO, IMPORT_VTO, N_COMP, T_COMP, ESTADO_UNIDADES, IMPORTE_VENCIMIENTO_UNIDADES, ID_CPA04)
			VALUES(
			'', @COD_PROVEE , '','PEN',  DATEADD(d, 30, @F_EMISION ), @IMPORTE_TOTAL , @NRO_FACTURA , 'FAC', 'PEN', @IMPORTE_TOTAL, @ID_CPA04)

			--ASIENTO_COMPROBANTE_CP
			set @ID_ASIENTO_COMPROBANTE_CP =  (SELECT MAX(ID_ASIENTO_COMPROBANTE_CP)+1 FROM ASIENTO_COMPROBANTE_CP)
			INSERT INTO ASIENTO_COMPROBANTE_CP (
			ID_ASIENTO_COMPROBANTE_CP, NCOMP_IN_C, ASIENTO_ANULACION, CONTABILIZADO, USUARIO_CONTABILIZACION, FECHA_CONTABILIZACION, TERMINAL_CONTABILIZACION, TRANSFERIDO_CN)
			VALUES (
			 @ID_ASIENTO_COMPROBANTE_CP, @NCOMP_IN_C ,'N','S',@NOMBRE_COMPLETO,@F_CONTABLE ,'PI','N')
			
			--ASIENTO_CP --RENGLON1
			set @ID_ASIENTO_CP =  (SELECT MAX(ID_ASIENTO_CP)+1 FROM ASIENTO_CP)
			INSERT INTO ASIENTO_CP (
			ID_ASIENTO_CP, ID_ASIENTO_COMPROBANTE_CP, NRO_RENGLON_ASIENTO_CP , ID_CUENTA, D_H, IMPORTE_RENGLON_BASE_CP, IMPORTE_RENGLON_ALTER_CP, DESC_LEYENDA, EDITA_CUENTA) 
			VALUES (
			@ID_ASIENTO_CP, @ID_ASIENTO_COMPROBANTE_CP, 1, @ID_CUENTA_PROVEEDORES, 'H', @IMPORTE_TOTAL, @IMPORTE_TOTAL,'PROVEEDORES VARIOS','N')

			IF @TIPO_FACTURA ='C' 
			BEGIN
				SET @ID_CUENTA_GASTO =(SELECT ID_CUENTA FROM CONCEPTO_CP WHERE COD_CPA45=@COD_CONCEPTO)
				---CPA47 RENGLON DE CONCEPTO
				INSERT INTO CPA47 (
				FILLER, COD_CONCEP, FECHA_MOV, IMPORTE_NE, IMPORT_PAN, IMP_NETO_P, NCOMP_IN_C, N_RENGL_C, TCOMP_IN_C, COD_CLASIF, 
				IMPORTE_EXENTO, IMPORTE_GRAVADO) 
				VALUES (
				'', @COD_CONCEPTO ,@F_CONTABLE ,@IMPORTE_GRAVADO + @IMPORTE_NO_GRAVADO , @IMPORTE_GRAVADO + @IMPORTE_NO_GRAVADO, @IMPORTE_GRAVADO + @IMPORTE_NO_GRAVADO , @NCOMP_IN_C , 1, @TCOMP_IN_C,'',
				@IMPORTE_NO_GRAVADO, @IMPORTE_GRAVADO)

				--CPA63
			
				SET @CLAS_SIAP = (SELECT ISNULL(CLAS_SIAP, 'SIN') CLAS_SIAP FROM CPA45 WHERE COD_CONCEP =@COD_CONCEPTO)
				

				--ASIENTO_CP --RENGLON 2 PARA CONCEPTO
				SET @ID_ASIENTO_CP=@ID_ASIENTO_CP+1
				INSERT INTO ASIENTO_CP (
				ID_ASIENTO_CP, ID_ASIENTO_COMPROBANTE_CP, NRO_RENGLON_ASIENTO_CP , ID_CUENTA, D_H, IMPORTE_RENGLON_BASE_CP, IMPORTE_RENGLON_ALTER_CP, DESC_LEYENDA, EDITA_CUENTA) 
				VALUES (
				@ID_ASIENTO_CP, @ID_ASIENTO_COMPROBANTE_CP, 2, @ID_CUENTA_GASTO, 'D', @IMPORTE_GRAVADO + @IMPORTE_NO_GRAVADO , @IMPORTE_GRAVADO + @IMPORTE_NO_GRAVADO ,'', 'N')
				--AUXILIAR
					
				
				SELECT @USA_AUX = USA_AUXILIARES_CONTABLES FROM CUENTA  WHERE ID_CUENTA = @ID_CUENTA_GASTO

				IF @usa_aux = 'S'
				BEGIN
					INSERT INTO AUXILIAR_ASIENTO_CP (
					ID_ASIENTO_CP, ID_AUXILIAR, PORC_APROPIACION, IMPORTE_RENGLON_BASE_CP, IMPORTE_RENGLON_ALTER_CP, EDITA_APROPIACION) 
					VALUES (
					@ID_ASIENTO_CP, @ID_AUXILIAR,100, @IMPORTE_GRAVADO + @IMPORTE_NO_GRAVADO ,@IMPORTE_GRAVADO + @IMPORTE_NO_GRAVADO,'N')
				END
			end
			ELSE --IF @TIPO_FACTURA ='R' 
			BEGIN
                --clas siap para luego usar en cpa63
				SET @CLAS_SIAP = (select top 1 isnull(sta11.CL_SIAP_CP,'SIN')  from RBA_TEMP_RENGLONES inner join sta11 on
				rba_temp_renglones.id_sta11 = sta11.id_sta11 where id_sesion= @ID_SESION)

				--CPA46 RENGLONES
				 INSERT INTO CPA46 (
					FILLER , CANTIDAD, COD_ARTICU, COD_DEPOSI,EQUIVALENC,
					FALTA_REM, FECHA_MOV,IMP_NETO_P, N_RENGL_C, NCOMP_IN_C,
					PORCE_DCTO, PRECIO_NET, PRECIO_PAN, TCOMP_IN_C, COD_CLASIF, 
					IMPORTE_EXENTO, IMPORTE_GRAVADO, ID_MEDIDA_COMPRA, ID_MEDIDA_STOCK, ID_MEDIDA_STOCK_2,
					CANTIDAD_2, FALTA_REM_2, UNIDAD_MEDIDA_SELECCIONADA, IMPORTE_FLETE, IMPORTE_IMPUESTOS_COSTOS,
					ID_STA11,  ID_CPA04, ID_CPA46)
					SELECT '', R.CANTIDAD, STA11.COD_ARTICU, 	@COD_DEPOSITO,1,
					0, @F_CONTABLE, r.PRECIO * R.CANTIDAD, r.n_renglon , @ncomp_in_c,
					0, r.precio, r.precio, @TCOMP_IN_C , '',
					0, r.PRECIO * R.CANTIDAD, NULL, STA11.ID_MEDIDA_STOCK, NULL,
					0, 0 , 'P', 0, 0,
					R.ID_STA11, @ID_CPA04, @ID_CPA46 + R.N_RENGLON 
					FROM RBA_TEMP_RENGLONES R  INNER JOIN STA11 ON R.ID_STA11 = STA11.ID_STA11 WHERE ID_SESION = @ID_SESION 

				
				IF EXISTS (SELECT TOP 1 * FROM  RBA_TEMP_RENGLONES R  INNER JOIN STA11 ON R.ID_STA11 = STA11.ID_STA11 WHERE ID_SESION = @ID_SESION AND STA11.STOCK=1) 
				BEGIN
					SET @NCOMP_IN_S = RIGHT('0000000' + (select CAST(isnull(max(cast(NComp_In_S as numeric)), 0)+1 AS VARCHAR) from STA14 where TComp_In_S ='FS'),8)
					INSERT INTO STA14 (
						FILLER, COD_PRO_CL, COTIZ, ESTADO_MOV,
						EXPORTADO, EXP_STOCK, FECHA_ANU, FECHA_MOV, HORA,
						LISTA_REM, LOTE, LOTE_ANU, MON_CTE, MOTIVO_REM,
						N_COMP, N_REMITO, NCOMP_IN_S, NCOMP_ORIG,NRO_SUCURS,
						OBSERVACIO, SUC_ORIG, T_COMP, TALONARIO, TCOMP_IN_S,
						TCOMP_ORIG, USUARIO, COD_TRANSP, HORA_COMP, ID_A_RENTA,
						DOC_ELECTR, COD_CLASIF, AUDIT_IMP, IMP_IVA, IMP_OTIMP,
						IMPORTE_BO, IMPORTE_TO, DIFERENCIA, SUC_DESTIN, T_DOC_DTE, 
						LEYENDA1, LEYENDA2, LEYENDA3, LEYENDA4, LEYENDA5,
						DCTO_CLIEN, T_INT_ORI, N_INT_ORI, FECHA_INGRESO, HORA_INGRESO,
						USUARIO_INGRESO, TERMINAL_INGRESO, IMPORTE_TOTAL_CON_IMPUESTOS, CANTIDAD_KILOS, ID_DIRECCION_ENTREGA,
						IMPORTE_GRAVADO, IMPORTE_EXENTO, ID_STA13, NRO_SUCURSAL_DESTINO_REMITO, ID_GVA14)
						VALUES ('', @COD_PROVEE, 1, 'F',
						0,0,'1800-01-01 00:00:00.000', @F_CONTABLE, '',
						0,0,0,1, '',
						@NRO_FACTURA , '', @NCOMP_IN_S , '', 0 ,
						'', 0, 'FAC', 0, 'FS',
						'', @NOMBRE_COMPLETO , '', '0000', 0,
						0, '', '', 0,0,
						0, @IMPORTE_TOTAL, 0, 0, '',
						'', '', '', '','',
						0, '','', CAST(GETDATE() AS DATE), LEFT(CONVERT(VARCHAR(8), GETDATE(), 108), 2) + SUBSTRING(CONVERT(VARCHAR(8), GETDATE(), 108), 4, 2),
						@NOMBRE_COMPLETO ,'PI', 0, 0, NULL,
						0, 0, NULL,  0, 0)

						DECLARE @ID_STA14 INT;
						SET @ID_STA14 = SCOPE_IDENTITY();
						--SELECT @ID_STA14 AS ID_STA14;

				INSERT INTO STA20 ( FILLER, CAN_EQUI_V, CANT_DEV, CANT_OC,CANT_PEND,
						CANT_SCRAP, CANTIDAD, COD_ARTICU, COD_DEPOSI, DEPOSI_DDE,
						EQUIVALENC, FECHA_MOV, N_ORDEN_CO, N_RENGL_OC, N_RENGL_S,
						NCOMP_IN_S, PLISTA_REM, PPP_EX, PPP_LO, PRECIO,
						PRECIO_REM, TCOMP_IN_S, TIPO_MOV, COD_CLASIF, CANT_FACTU,
						DCTO_FACTU, CANT_DEV_2, CANT_PEND_2, CANTIDAD_2, CANT_FACTU_2,
						
						ID_MEDIDA_STOCK_2, ID_MEDIDA_STOCK, ID_MEDIDA_VENTAS, ID_MEDIDA_COMPRA, UNIDAD_MEDIDA_SELECCIONADA, 
						PRECIO_REMITO_VENTAS, CANT_OC_2, RENGL_PADR,COD_ARTICU_KIT,	PROMOCION, 
						PRECIO_ADICIONAL_KIT, TALONARIO_OC, ID_STA11, ID_STA14, COD_DEPOSI_INGRESO, 
						OBSERVACIONES)
						SELECT '', R.CANTIDAD , 0, 0, 0,
						0, R.CANTIDAD, 	STA11.COD_ARTICU, 	@COD_DEPOSITO, '',
						1, @F_CONTABLE, '', 0, r.n_renglon ,
						@NCOMP_IN_S, 0, 0,0, R.PRECIO, 
						0,'FS', 'E', '', R.CANTIDAD,
						0,0,0,0,0,
						NULL, STA11.ID_MEDIDA_STOCK, NULL,  NULL, 'P',
						0, 0, 0, '', 0,
						0, 0, R.ID_STA11, @ID_STA14 , @COD_DEPOSITO, 
						''
						FROM RBA_TEMP_RENGLONES R  INNER JOIN STA11 ON R.ID_STA11 = STA11.ID_STA11 WHERE ID_SESION = @ID_SESION  AND STOCK=1
							
				update sta19 set sta19.CANT_STOCK =cant_calculada from 
					sta19 inner join (select cod_articu,
					SUM((case sta20.TIPO_MOV when 'E' THEN 1 WHEN 'S' THEN -1 ELSE 0 END )* CANTIDAD ) cant_calculada
					from sta20  where COD_DEPOSI =@COD_DEPOSITO 
					GROUP BY COD_ARTICU) SALDOS ON SALDOS.COD_ARTICU =STA19.COD_ARTICU 
					WHERE sta19.CANT_STOCK <>cant_calculada and COD_DEPOSI =@COD_DEPOSITO 
					
					insert into cpa48 (	
					FILLER, CANTIDAD, N_RENGL_C, N_RENGL_S,  NCOMP_IN_C,
					NCOMP_IN_S, TCOMP_IN_C, TCOMP_IN_S, CANTIDAD_2)
					select '' , sta20.CANTIDAD , sta20.N_RENGL_S , sta20.N_RENGL_S , @NCOMP_IN_C ,
					@ncomp_in_s, @TCOMP_IN_C, 'FS', 0 FROM STA20 WHERE NCOMP_IN_S =@NCOMP_IN_S  AND TCOMP_IN_S ='FS'

					

					---ASIENTO_CP
					
					SET @ID_ASIENTO_CP  =  (SELECT MAX(ID_ASIENTO_CP) FROM ASIENTO_CP)
					
					INSERT INTO ASIENTO_CP 
						(ID_ASIENTO_CP, 
						ID_ASIENTO_COMPROBANTE_CP, 
						NRO_RENGLON_ASIENTO_CP, 
						ID_CUENTA, D_H ,
						IMPORTE_RENGLON_BASE_CP , IMPORTE_RENGLON_ALTER_CP , DESC_LEYENDA, EDITA_CUENTA )
					SELECT  
						@ID_ASIENTO_CP + ROW_NUMBER() OVER (ORDER BY @ID_SESION ASC) ID_ASIENTO_CP  , 
						--914,
						@ID_ASIENTO_COMPROBANTE_CP  ID_ASIENTO_COMPROBANTE_CP , 
						2 + ROW_NUMBER() OVER (ORDER BY @ID_SESION ASC) AS RENGLON, 
						
						ISNULL(ID_CUENTA_COMPRAS , @ID_CUENTA_SB ), 'D',
						SUM(R.PRECIO * CANTIDAD) AS  IMPORTE_RENGLON_BASE_CP, SUM(R.PRECIO * CANTIDAD) AS IMPORTE_RENGLON_ALTER_CP , 
						'', 'N'
						FROM  RBA_TEMP_RENGLONES R LEFT JOIN ARTICULO_CUENTA ON
						R.ID_STA11 = ARTICULO_CUENTA.ID_STA11 
						WHERE ID_SESION = @ID_SESION  
						GROUP BY  ISNULL(ARTICULO_CUENTA.ID_CUENTA_COMPRAS , @ID_CUENTA_SB)
						--AUXILIAR
						insert into auxiliar_asiento_cp (ID_ASIENTO_CP, ID_AUXILIAR , PORC_APROPIACION , IMPORTE_RENGLON_BASE_CP, IMPORTE_RENGLON_ALTER_CP )
						SELECT id_asiento_cp, @ID_AUXILIAR , 100, IMPORTE_RENGLON_BASE_CP, IMPORTE_RENGLON_ALTER_CP  
						FROM ASIENTO_CP inner join cuenta on asiento_cp.ID_CUENTA = cuenta.ID_CUENTA 
						where ID_ASIENTO_COMPROBANTE_CP =@ID_ASIENTO_COMPROBANTE_CP  and cuenta.USA_AUXILIARES_CONTABLES ='S'
						ORDER BY ID_ASIENTO_CP	
				
				
				END
			END
			
			
						
			SET @ID_ASIENTO_CP  =  (SELECT MAX(ID_ASIENTO_CP) FROM ASIENTO_CP)
			

			--ASIENTO_CP --RENGLON 3 -IVA
			DECLARE @RENGLON_IMPUESTO AS INTEGER
			
			SET @RENGLON_IMPUESTO=3

			IF	@CLAS_SIAP ='SIN' 
					SET @CLAS_SIAP = (SELECT ISNULL(CLAS_SIAP,'SIN') FROM CPA01 WHERE COD_PROVEE= @COD_PROVEE)


			IF  (@IMPORTE_IVA_105) >0 
			begin
				SET @ID_ASIENTO_CP=@ID_ASIENTO_CP+1

				SET @ID_CUENTA_IVA=(SELECT ID_CUENTA FROM RENGLON_MODELO_CP  inner join TIPO_CONTABLE on RENGLON_MODELO_CP.ID_TIPO_CONTABLE =tipo_contable.ID_TIPO_CONTABLE 
				where id_asiento_modelo_cp=@ID_ASIENTO_MODELO_CP and COD_TIPO_CONTABLE =@COD_IVA_105)

				INSERT INTO ASIENTO_CP (
				ID_ASIENTO_CP, ID_ASIENTO_COMPROBANTE_CP, NRO_RENGLON_ASIENTO_CP , ID_CUENTA, D_H, IMPORTE_RENGLON_BASE_CP, IMPORTE_RENGLON_ALTER_CP, DESC_LEYENDA, EDITA_CUENTA) 
				VALUES (
				@ID_ASIENTO_CP, @ID_ASIENTO_COMPROBANTE_CP, @RENGLON_IMPUESTO, @ID_CUENTA_IVA, 'D', @IMPORTE_IVA_105 , @IMPORTE_IVA_105 ,'','N')
				SET @RENGLON_IMPUESTO=@RENGLON_IMPUESTO+1
				
			
				INSERT INTO CPA63 (
					FILLER, CLAS_SIAP, IMPORTE, NCOMP_IN_C, PORC_ALICU, TCOMP_IN_C) 
					VALUES (
					'',@CLAS_SIAP,@IMPORTE_IVA_105,@NCOMP_IN_C ,10.5,@TCOMP_IN_C)
			end

			IF  (@IMPORTE_IVA_21) >0 
			begin
				SET @ID_ASIENTO_CP=@ID_ASIENTO_CP+1
				SET @ID_CUENTA_IVA=(SELECT ID_CUENTA FROM RENGLON_MODELO_CP  inner join TIPO_CONTABLE on RENGLON_MODELO_CP.ID_TIPO_CONTABLE =tipo_contable.ID_TIPO_CONTABLE 
				where id_asiento_modelo_cp=@ID_ASIENTO_MODELO_CP and COD_TIPO_CONTABLE =@COD_IVA_21)

				INSERT INTO ASIENTO_CP (
				ID_ASIENTO_CP, ID_ASIENTO_COMPROBANTE_CP, NRO_RENGLON_ASIENTO_CP , ID_CUENTA, D_H, IMPORTE_RENGLON_BASE_CP, IMPORTE_RENGLON_ALTER_CP, DESC_LEYENDA, EDITA_CUENTA) 
				VALUES (
				@ID_ASIENTO_CP, @ID_ASIENTO_COMPROBANTE_CP, @RENGLON_IMPUESTO, @ID_CUENTA_IVA, 'D', @IMPORTE_IVA_21 ,  @IMPORTE_IVA_21 ,'','N')
				SET @RENGLON_IMPUESTO=@RENGLON_IMPUESTO+1

				INSERT INTO CPA63 (
					FILLER, CLAS_SIAP, IMPORTE, NCOMP_IN_C, PORC_ALICU, TCOMP_IN_C) 
					VALUES (
					'',@CLAS_SIAP,@IMPORTE_IVA_21,@NCOMP_IN_C ,21,@TCOMP_IN_C)
			end

			IF  (@IMPORTE_IVA_27) >0 
			begin
				SET @ID_ASIENTO_CP=@ID_ASIENTO_CP+1
				SET @ID_CUENTA_IVA=(SELECT ID_CUENTA FROM RENGLON_MODELO_CP  inner join TIPO_CONTABLE on RENGLON_MODELO_CP.ID_TIPO_CONTABLE =tipo_contable.ID_TIPO_CONTABLE 
				where id_asiento_modelo_cp=@ID_ASIENTO_MODELO_CP and COD_TIPO_CONTABLE =@COD_IVA_27)

				INSERT INTO ASIENTO_CP (
				ID_ASIENTO_CP, ID_ASIENTO_COMPROBANTE_CP, NRO_RENGLON_ASIENTO_CP , ID_CUENTA, D_H, IMPORTE_RENGLON_BASE_CP, IMPORTE_RENGLON_ALTER_CP, DESC_LEYENDA, EDITA_CUENTA) 
				VALUES (
				@ID_ASIENTO_CP, @ID_ASIENTO_COMPROBANTE_CP, @RENGLON_IMPUESTO, @ID_CUENTA_IVA, 'D', @IMPORTE_IVA_27 ,@IMPORTE_IVA_27,'','N')
				SET @RENGLON_IMPUESTO=@RENGLON_IMPUESTO+1

				INSERT INTO CPA63 (
					FILLER, CLAS_SIAP, IMPORTE, NCOMP_IN_C, PORC_ALICU, TCOMP_IN_C) 
					VALUES (
					'',@CLAS_SIAP,@IMPORTE_IVA_27,@NCOMP_IN_C ,27,@TCOMP_IN_C)
			end
			IF  (@IMPORTE_PERCEPCION ) >0 
			begin
				SET @ID_ASIENTO_CP=@ID_ASIENTO_CP+1
				SET @ID_CUENTA_IVA=(SELECT ID_CUENTA FROM RENGLON_MODELO_CP  inner join TIPO_CONTABLE on RENGLON_MODELO_CP.ID_TIPO_CONTABLE =tipo_contable.ID_TIPO_CONTABLE 
				where id_asiento_modelo_cp=@ID_ASIENTO_MODELO_CP and COD_TIPO_CONTABLE =CAST(@COD_PERCEPCION AS VARCHAR) )

				INSERT INTO ASIENTO_CP (
				ID_ASIENTO_CP, ID_ASIENTO_COMPROBANTE_CP, NRO_RENGLON_ASIENTO_CP , ID_CUENTA, D_H, IMPORTE_RENGLON_BASE_CP, IMPORTE_RENGLON_ALTER_CP, DESC_LEYENDA, EDITA_CUENTA) 
				VALUES (
				@ID_ASIENTO_CP, @ID_ASIENTO_COMPROBANTE_CP, @RENGLON_IMPUESTO, @ID_CUENTA_IVA, 'D', @IMPORTE_PERCEPCION ,@IMPORTE_PERCEPCION,'','N')
			
			end

			IF  (@IMPORTE_PERCEPCION2 ) >0 
			begin
				SET @ID_ASIENTO_CP=@ID_ASIENTO_CP+1
				SET @ID_CUENTA_IVA=(SELECT ID_CUENTA FROM RENGLON_MODELO_CP  inner join TIPO_CONTABLE on RENGLON_MODELO_CP.ID_TIPO_CONTABLE =tipo_contable.ID_TIPO_CONTABLE 
				where id_asiento_modelo_cp=@ID_ASIENTO_MODELO_CP and COD_TIPO_CONTABLE =CAST(@COD_PERCEPCION2 AS VARCHAR) )

				INSERT INTO ASIENTO_CP (
				ID_ASIENTO_CP, ID_ASIENTO_COMPROBANTE_CP, NRO_RENGLON_ASIENTO_CP , ID_CUENTA, D_H, IMPORTE_RENGLON_BASE_CP, IMPORTE_RENGLON_ALTER_CP, DESC_LEYENDA, EDITA_CUENTA) 
				VALUES (
				@ID_ASIENTO_CP, @ID_ASIENTO_COMPROBANTE_CP, @RENGLON_IMPUESTO, @ID_CUENTA_IVA, 'D', @IMPORTE_PERCEPCION2 ,@IMPORTE_PERCEPCION2,'','N')
			
			end
			EXECUTE P_UPDATESEQUENCEBYTABLENAME 'ASIENTO_COMPROBANTE_CP'
			EXECUTE P_UPDATESEQUENCEBYTABLENAME 'ASIENTO_CP'
			EXECUTE P_UPDATESEQUENCEBYTABLENAME 'CPA46'
	END

            COMMIT
            END TRY

            BEGIN CATCH
                ROLLBACK;

                SET @NCOMP_IN_C = 0
            	SET @RESULTADO = 'ERROR: ' + (SELECT CAST(ERROR_NUMBER() AS VARCHAR) +'- ' + ERROR_MESSAGE() AS VARCHAR)
            END CATCH


            SELECT @RESULTADO  as RESULTADO, @NCOMP_IN_C as  NCOMP_IN_C
